services:
  database:
    image: postgres
    container_name: portal_postgres
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: portal_db_adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  bot:
    build: .
    container_name: portal_bot
    restart: always
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.prod
    environment:
      - ENV=prod
      - DB_HOST=database
    volumes:
      - .:/app
    command: python main.py

volumes:
  postgres_data:
