version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: portal_postgres
    restart: always
    environment:
      POSTGRES_DB: portal_db
      POSTGRES_USER: portal_user
      POSTGRES_PASSWORD: portal_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: portal_bot
    restart: always
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: postgres
      DB_NAME: portal_db
      DB_USER: portal_user
      DB_PASSWORD: portal_password
    command: python aiogram_run.py

volumes:
  postgres_data:
