services:
  database:
    image: postgres
    container_name: portal_postgres
    restart: always
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  bot:
    build: .
    container_name: portal_bot
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      TZ: Europe/Moscow
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
    command: watchmedo auto-restart --patterns="*.py" --recursive -- python aiogram_run.py

volumes:
  postgres_data:
